-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 22:26:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`citites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`citites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'список городов сайта';


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `city_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `birthday` DATE NULL,
  `description` TEXT NULL,
  `password_hash` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `skype` VARCHAR(45) NULL,
  `telegram` VARCHAR(45) NULL,
  `avatar` VARCHAR(45) NULL,
  `notification_new_message` VARCHAR(45) NULL,
  `notification_task_action` VARCHAR(45) NULL,
  `notification_new_review` VARCHAR(45) NULL,
  `notification_show_contact` VARCHAR(45) NULL,
  `notification_not_show_profile` VARCHAR(45) NULL,
  `type` VARCHAR(45) NOT NULL,
  `time_active` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `citites_id`),
  INDEX `fk_users_citites_idx` (`citites_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_citites`
    FOREIGN KEY (`citites_id`)
    REFERENCES `mydb`.`citites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'пользователи сайта';


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `alias` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'список категорий задания и их название в качестве специализации для юзера';


-- -----------------------------------------------------
-- Table `mydb`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `period_execution` DATE NULL,
  `city_id` INT NOT NULL,
  `description` TEXT NOT NULL,
  `icon` VARCHAR(45) NOT NULL,
  `price` INT NULL,
  `specialization_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `coord_x` VARCHAR(45) NULL,
  `coord_y` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `author_id` INT NOT NULL,
  `executor_id` INT NULL,
  PRIMARY KEY (`id`, `citites_id`, `specializations_id`, `author_id`, `executor_id`),
  INDEX `fk_tasks_citites1_idx` (`citites_id` ASC) VISIBLE,
  INDEX `fk_tasks_specializations1_idx` (`specializations_id` ASC) VISIBLE,
  INDEX `fk_tasks_users1_idx` (`author_id` ASC) VISIBLE,
  INDEX `fk_tasks_users2_idx` (`executor_id` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_citites1`
    FOREIGN KEY (`citites_id`)
    REFERENCES `mydb`.`citites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_specializations1`
    FOREIGN KEY (`specializations_id`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_users1`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_users2`
    FOREIGN KEY (`executor_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'задания';


-- -----------------------------------------------------
-- Table `mydb`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `tasks_id`),
  INDEX `fk_files_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_files_tasks1_idx` (`tasks_id` ASC) VISIBLE,
  CONSTRAINT `fk_files_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_files_tasks1`
    FOREIGN KEY (`tasks_id`)
    REFERENCES `mydb`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'файлы сайта';


-- -----------------------------------------------------
-- Table `mydb`.`task_responce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`task_responce` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `executor_id` INT NOT NULL,
  `price` INT NOT NULL,
  `text` TEXT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `tasks_id`, `executor_id`),
  INDEX `fk_task_responce_tasks1_idx` (`tasks_id` ASC) VISIBLE,
  INDEX `fk_task_responce_users1_idx` (`executor_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_responce_tasks1`
    FOREIGN KEY (`tasks_id`)
    REFERENCES `mydb`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_responce_users1`
    FOREIGN KEY (`executor_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'отклики на задание исполнителем';


-- -----------------------------------------------------
-- Table `mydb`.`task_chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`task_chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `executor_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  PRIMARY KEY (`id`, `executor_id`, `tasks_id`, `tasks_author_id`),
  INDEX `fk_task_chat_users1_idx` (`executor_id` ASC) VISIBLE,
  INDEX `fk_task_chat_tasks1_idx` (`tasks_id` ASC, `tasks_author_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_chat_users1`
    FOREIGN KEY (`executor_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_chat_tasks1`
    FOREIGN KEY (`tasks_id` , `tasks_author_id`)
    REFERENCES `mydb`.`tasks` (`id` , `author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'чат по заданию между исполнителем и заказчиком';


-- -----------------------------------------------------
-- Table `mydb`.`user_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tasks_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `text` TEXT NULL,
  `rating` INT NULL,
  PRIMARY KEY (`id`, `tasks_id`, `tasks_author_id`, `user_id`),
  INDEX `fk_user_review_tasks1_idx` (`tasks_id` ASC, `tasks_author_id` ASC) VISIBLE,
  INDEX `fk_user_review_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_review_tasks1`
    FOREIGN KEY (`tasks_id` , `tasks_author_id`)
    REFERENCES `mydb`.`tasks` (`id` , `author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_review_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'отзывы на пользователя при завершении задания';


-- -----------------------------------------------------
-- Table `mydb`.`user_favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_favorite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `favorite_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `favorite_id`),
  INDEX `fk_user_favorite_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_favorite_users2_idx` (`favorite_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_favorite_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_favorite_users2`
    FOREIGN KEY (`favorite_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'избранные пользователи для юзера';


-- -----------------------------------------------------
-- Table `mydb`.`user_specialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_specialization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `categories_id`, `users_id`),
  INDEX `fk_user_specialization_categories1_idx` (`categories_id` ASC) VISIBLE,
  INDEX `fk_user_specialization_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_specialization_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_specialization_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'таблица хранящаяя все выбранные пользователем специализации';


-- -----------------------------------------------------
-- Table `mydb`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status_send` VARCHAR(45) NOT NULL,
  `status_show` VARCHAR(45) NOT NULL,
  `task_chat_id` INT NOT NULL,
  `task_responce_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `task_chat_id`, `task_responce_id`, `tasks_id`, `users_id`),
  INDEX `fk_notification_task_chat1_idx` (`task_chat_id` ASC) VISIBLE,
  INDEX `fk_notification_task_responce1_idx` (`task_responce_id` ASC) VISIBLE,
  INDEX `fk_notification_tasks1_idx` (`tasks_id` ASC) VISIBLE,
  INDEX `fk_notification_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_notification_task_chat1`
    FOREIGN KEY (`task_chat_id`)
    REFERENCES `mydb`.`task_chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_task_responce1`
    FOREIGN KEY (`task_responce_id`)
    REFERENCES `mydb`.`task_responce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_tasks1`
    FOREIGN KEY (`tasks_id`)
    REFERENCES `mydb`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'тут хранятся уведомления для пользователя';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
