<?php

namespace frontend\models\db;

use Yii;
use yii\behaviors\TimestampBehavior;
use frontend\models\db\Tasks;
use common\models\User;

/**
 * This is the model class for table "messages".
 *
 * @property int $id
 * @property int|null $task_id
 * @property int|null $user_id
 * @property string|null $message
 * @property int|null $published_at
 * @property boolean|null $is_mine
 *
 * @property Tasks $task
 */
class Messages extends \yii\db\ActiveRecord
{
    public $is_mine = false;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'messages';
    }

    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    \yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['published_at'],
                ],
                'value' => new \yii\db\Expression('NOW()'),
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['task_id', 'user_id'], 'integer'],
            [['message', 'published_at'], 'string'],
            [['is_mine'], 'boolean'],
            [['task_id'], 'exist', 'skipOnError' => false, 'targetClass' => Tasks::class, 'targetAttribute' => ['task_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => false, 'targetClass' => User::class, 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'task_id' => 'Task ID',
            'message' => 'Message',
            'timestamp' => 'Timestamp',
        ];
    }

    /**
     * Gets query for [[Task]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTask()
    {
        return $this->hasOne(Tasks::class, ['id' => 'task_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    public function beforeSave($insert)
    {
        if($this->user_id == $this->task->customer_id)
            $this->is_mine = true;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
